### ISSUE TITLE
mapping to MEDDRA identifiers?

### ISSUE THREAD

**Issue by elipapa** [opentargets/platform-etl-openfda-faers#17]
have you considered mapping the adverse event term to their MEDDRA ids? This will help linking this data and make it more interoperable.

**Comment by d0choa** [comment]
@mkarmona raised the issue when we were processing the data for the first time. At that stage, we were still working on the prototype, so we considered it low priority. Now, I would agree we could benefit from id mappings to Meddra and the task should be trivial. For the platform will also be potentially useful to link them back to HPO/EFO.

Unfortunately, we have no experience with downloading or processing Meddra. I'm assuming the lookup table we would need has no restrictive license, but we will need to investigate this. Any advice on this would be useful @elipapa

**Comment by andrewhercules** [comment]
Closing ticket on this repo and reposting to the issue tracker - see https://github.com/opentargets/platform/issues/1205
